# Generated by Django 3.2.8 on 2021-10-12 23:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AndroidAssetBundle', models.URLField(max_length=2048)),
                ('destination', jsonfield.fields.JSONField()),
                ('endTime', models.FloatField()),
                ('iOSAssetBundle', models.URLField(max_length=2048)),
                ('loopCount', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('startTime', models.FloatField()),
                ('trim', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('blend', models.CharField(choices=[('REACTION', 'Reaction'), ('BURPEE', 'Burpee')], max_length=9)),
                ('stitch', models.CharField(choices=[('REACTION', 'Reaction'), ('BURPEE', 'Burpee')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('effectType', models.CharField(max_length=50)),
                ('prefabName', models.CharField(max_length=25)),
                ('iOSBundleUrl', models.URLField()),
                ('androidBundleUrl', models.URLField()),
                ('transform', jsonfield.fields.JSONField()),
                ('startTime', models.IntegerField()),
                ('endTime', models.IntegerField()),
                ('loop', models.BooleanField()),
                ('identifiableSurfaces', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('POINT', 'Point'), ('AREA', 'Area'), ('SUN', 'Sun')], max_length=50)),
                ('range', models.IntegerField()),
                ('startTime', models.IntegerField()),
                ('endTime', models.IntegerField()),
                ('intensity', models.FloatField()),
                ('indirectMultiplier', models.IntegerField()),
                ('mode', models.CharField(choices=[('REALTIME', 'RealTime'), ('Delay', 'Delay')], max_length=50)),
                ('lightMapUrl', models.URLField(max_length=2048)),
                ('shadowType', models.CharField(choices=[('SOFT', 'SOFT'), ('NORMAL', 'NORMAL'), ('NONE', 'NONE')], max_length=50)),
                ('shadowStrength', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('exposure', models.CharField(max_length=30)),
                ('localPosition', jsonfield.fields.JSONField()),
                ('localRotation', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startPointId', models.IntegerField()),
                ('duration', models.PositiveIntegerField()),
                ('loopCount', models.PositiveIntegerField()),
                ('pathType', models.CharField(max_length=255)),
                ('orientationType', models.CharField(choices=[('LookAhead', 'LookAhead'), ('lookAtTarget', 'lookAtTarget'), ('lookAtPosition', 'lookAtPosition')], max_length=50)),
                ('entityOrientation', jsonfield.fields.JSONField()),
                ('easeType', models.CharField(choices=[('OutFlash', 'OutFlash'), ('InFlash', 'InFlash')], max_length=50)),
                ('isSpeedBased', models.BooleanField()),
                ('lookAtValue', models.FloatField()),
                ('waypoints', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectName', models.CharField(max_length=255)),
                ('audioUrl', models.URLField(max_length=2048)),
                ('loopCount', models.PositiveIntegerField()),
                ('volume', models.FloatField()),
                ('pitch', models.FloatField()),
                ('startTime', models.PositiveIntegerField()),
                ('endTime', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TextToSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('endTime', models.FloatField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=50)),
                ('startTime', models.FloatField()),
                ('text', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('SPECIFIC', 'Specific'), ('NORMAL', 'Normal')], max_length=50)),
                ('voiceEffect', models.CharField(choices=[('NONE', 'None'), ('SHADY', 'Shady'), ('THIN', 'Thin')], max_length=50)),
                ('voiceName', models.CharField(max_length=255)),
                ('voiceVolume', models.PositiveIntegerField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.language')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.FloatField()),
                ('type', models.CharField(choices=[('CHARACTER', 'Character')], max_length=50)),
                ('objectDbHash', models.CharField(max_length=255)),
                ('AndroidAssetBundle', models.URLField()),
                ('endTime', models.FloatField()),
                ('iOSAssetBundle', models.URLField()),
                ('objectId', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('layer', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=255)),
                ('origin', jsonfield.fields.JSONField()),
                ('animation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='root.animation')),
                ('effect', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='root.effect')),
                ('light', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='root.light')),
                ('movement', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='root.movement')),
                ('sound', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='root.sound')),
                ('textToSpeech', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='root.texttospeech')),
            ],
        ),
    ]
