# Generated by Django 3.2.8 on 2021-10-06 20:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AndroidAssetBundle', models.URLField(max_length=2048)),
                ('destination', jsonfield.fields.JSONField()),
                ('endTime', models.PositiveIntegerField()),
                ('iOSAssetBundle', models.URLField(max_length=2048)),
                ('loopCount', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('startTime', models.IntegerField()),
                ('trim', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('blend', models.CharField(choices=[('REACTION', 'Reaction'), ('BURPEE', 'Burpee')], max_length=9)),
                ('stitch', models.CharField(choices=[('REACTION', 'Reaction'), ('BURPEE', 'Burpee')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('animation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='root.animation')),
                ('movement', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='root.movement')),
            ],
        ),
    ]
