# Generated by Django 3.2.8 on 2021-10-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='audioType',
            field=models.CharField(choices=[('M4A', 'M4A'), ('MPEG', 'MPEG'), ('AAC', 'AAC'), ('WAV', 'WAV')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='effect',
            name='effectType',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('2D/3D', '2D/3D')], max_length=50),
        ),
    ]
