# Generated by Django 3.2.8 on 2022-01-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_useraccount_testfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='moroccan',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phone_number',
            field=models.CharField(default='06123456789', max_length=255),
        ),
    ]
